"""empty message

Revision ID: 33819ec2a61a
Revises: 
Create Date: 2017-02-22 20:06:28.707071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33819ec2a61a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bucketlists_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bucketlists_count')
    # ### end Alembic commands ###
