"""empty message

Revision ID: d7c4da554409
Revises: 33819ec2a61a
Create Date: 2017-02-22 20:32:25.160536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c4da554409'
down_revision = '33819ec2a61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('items_count', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('item_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_id')
    op.drop_column('bucketlist', 'items_count')
    # ### end Alembic commands ###
